---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-auth-jiayi-com-v1-authcenter
  failurePolicy: Fail
  name: mauthcenter.kb.io
  rules:
  - apiGroups:
    - auth.jiayi.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - authcenters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-auth-jiayi-com-v1-authcenter
  failurePolicy: Fail
  name: vauthcenter.kb.io
  rules:
  - apiGroups:
    - auth.jiayi.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - authcenters
  sideEffects: None
