# permissions for end users to edit authcenters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: authcenter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: auth-center
    app.kubernetes.io/part-of: auth-center
    app.kubernetes.io/managed-by: kustomize
  name: authcenter-editor-role
rules:
- apiGroups:
  - auth.jiayi.com
  resources:
  - authcenters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.jiayi.com
  resources:
  - authcenters/status
  verbs:
  - get
